### ISSUE TITLE
Specifying a PATCH input_filter_spec ignores required fields

### ISSUE THREAD

**Issue by intellix** [zfcampus/zf-content-validation#16]
Was attempting to create a PATCH `input_filter_spec` that requires the request to include a particular field. 

**Use case:** I have a PasswordResetRequest entity that when created sends a random hash to an email. The user clicks this link and my frontend app makes a PATCH request to change the password and set it to used at the same time. I can do this manually but still think it should be possible to require fields for PATCH requests.

``` php
'MyApp\\V1\\Rest\\PasswordResetRequest\\PatchValidator' => array(
    0 => array(
        'name' => 'used',
        'required' => true,
        'filters' => array(),
        'validators' => array(),
        'allow_empty' => false,
        'continue_if_empty' => false,
    ),
    1 => array(
        'name' => 'new_password',
        'required' => true,
        'filters' => array(),
        'validators' => array(
            0 => array(
                'name' => 'Zend\\Validator\\StringLength',
                'options' => array(
                    'min' => '6',
                ),
            ),
        ),
        'allow_empty' => false,
        'continue_if_empty' => false,
    ),
),
```

It seems that https://github.com/zfcampus/zf-content-validation/blob/master/src/ContentValidationListener.php#L166 is the culprit, overriding what I've specified with unrequired fields

**Comment by hrayrpapikyan** [comment]
So you just ignore 'required' => true in case of PATCH requests?
@intellix have you implemented a solution for this or just added validation logic to your resources?

**Comment by intellix** [comment]
@hrayrpapikyan I'm not quite sure as I've moved away from REST and to GraphQL and no longer use ZF2/Apigility.

Looking at my old code it looks like I am validating it directly in the resources as I guess that's the only way :)

**Comment by Wilt** [comment]
If you don't want to solve this inside your listener, an alternative solution would be to make your own `InputFilter` class where you overwrite the existing `setValidationGroup` method that doesn't allow setting the group to anything other then VALIDATE_ALL:

    /**
     * Don't allow ContentValidationListener::validatePatch to set validation group
     *
     * @param mixed $group
     * @return InputFilterInterface
     */
    public function setValidationGroup($group)
    {
        $group = self::VALIDATE_ALL;
        return parent::setValidationGroup($group);
    }

I am also thinking of providing a PR with an alternative solution that can be configurable, but for now this is how I quickly resolved the issue in those cases where I want to validate more then just the provided data (required fields that aren't present in the data).
