### ISSUE TITLE
Factory construct without passing InputFilterManager, by design? 

### ISSUE THREAD

**Issue by foalford** [zfcampus/zf-content-validation#25]
I wonder if the [contruction of InputFilter/Factory](https://github.com/zfcampus/zf-content-validation/blob/master/src/InputFilter/InputFilterAbstractServiceFactory.php#L74) without injecting a InputFilterPluginManager is by design or not. It ends up using another instance, which has no clue of configurations within module.config.php.

In addition, there is a use case, [to reuse InputFilters definition](http://youpolar.com/inputfilters-myth) that I think would be reasonable. Is it worth of having a look?

**Comment by Barbarrosa** [comment]
It looks like [this pull request](https://github.com/zfcampus/zf-content-validation/pull/31) might address the issue.
