### ISSUE TITLE
Unable to add dynamic data to InputFilter

### ISSUE THREAD

**Issue by steverhoades** [zfcampus/zf-content-validation#37]
Please see issue discussed here:
https://groups.google.com/a/zend.com/forum/#!searchin/apigility-users/NoRecordExists/apigility-users/rXdgqYP4PLw/3w-OK-7GtSEJ

There is currently no way to inject dynamic values into the InputFilter.  One valid use case is the NoRecordExists validator where you may be checking uniqueness but need to exclude values that belong to an existing record IE> PUT.

**Comment by weierophinney** [comment]
It looks like this is solved with #38! :)
