### ISSUE TITLE
How to validate nested data following Apigility way?

### ISSUE THREAD

**Issue by diwms** [zfcampus/zf-content-validation#43]
Hi. I have one small question about validating nested json data. For example, I have similar **PATCH** request as this:

```json
{
 "awesome": "yes",
  "myObject": {
    "some_property": "Text Example value",
    "another_property": "1965"
  }
}
```

What is the proper and maybe correct way to set filters and validators for this fields **some_property** and **another_property** ?

Thanks a lot for answers

**Comment by diwms** [comment]
Ok. Thanks

**Comment by nobesnickr** [comment]
Was this answered? If so can you post the answer or reference? I have a similar question I am researching

**Comment by Wilt** [comment]
Check for similar questions and answers to such questions also [StackOverflow under the `Apigility` tag](http://stackoverflow.com/questions/tagged/apigility)
I regularly check and try to answer there. Here also a link to similar question that I answered which might help you: http://stackoverflow.com/a/29674672/1697459
