### ISSUE TITLE
After upgrade to ZF2 2.4 and latest apigility some non-required fields report as required

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-content-validation#46]
It appears that some of my older fields that are "required" => false for validation also have values for "allow_empty" => false and "continue_if_empty" => false.

It seems related to this change: https://github.com/zendframework/zf2/pull/7056/files#diff-eba196bb0648a9366fa5c59a0edb701bR322

But essentially any of my non-required fields which have a value of allow_empty = false will now show up as required fields in the API response.

**Comment by weierophinney** [comment]
Based on discussion on IRC, the only issue is when `allow_empty => false` and `required => false`.

**Comment by dstockto** [comment]
Also ```allow_empty => false``` with ```continue_if_empty => false``` is broken. If ```continue_if_empty``` is true then it is working.

**Comment by weierophinney** [comment]
@dstockto Can you create a grid of the cases that do and do not work for you? I specifically want to see the following:

- `required => false, allow_empty => false, continue_if_empty => false`
- `required => false, allow_empty => false, continue_if_empty => true`
- `required => false, allow_empty => true, continue_if_empty => false`
- `required => false, allow_empty => true, continue_if_empty => true`

Thanks!

**Comment by dstockto** [comment]
@weierophinney Here you are:

* ```required => false, allow_empty => false, continue_if_empty => false **FAIL** ```
* ```required => false, allow_empty => false, continue_if_empty => true SUCCESS ```
* ```required => false, allow_empty => true, continue_if_empty => false SUCCESS ```
* ```required => false, allow_empty => true, continue_if_empty => true SUCCESS ```

For bonus:

* ```required => false, allow_empty => false **FAIL** ```
* ```required => false, allow_empty => true SUCCESS```
* ```required => false, continue_if_empty => false SUCCESS```
* ```required => false, continue_if_empty => true SUCCESS```

**Comment by weierophinney** [comment]
@dstockto Whoa… did not expect those results; I expected that any time `allow_empty` was `false`, we'd see failure, but to see it's only an issue if `continue_if_empty` is `false` *simultaneously* is strange; that means there's an even bigger regression, as `Zend\Filter\Input` must not be handling that condition.

On a little inspection of the ZF2 issue tracker, I found this:

- https://github.com/zendframework/zf2/issues/7445

There's a related pull request I'm commenting on and assisting with here:

- https://github.com/zendframework/zf2/pull/7448

At this point, I think we need to get that fixed; I don't think there's a solution we can perform in zf-content-validation itself.

**Comment by dstockto** [comment]
No worries. I fixed all of the issues I had with my older APIs by removing allow_empty and continue_if_empty from all of my non-required field definitions.

**Comment by weierophinney** [comment]
@dstockto — I've got a patch in place for ZF2:

- https://github.com/zendframework/zf2/pull/7474

You can test it by adding a `repositories` section to your `composer.json`:

```json
"repositories": [
    { "type": "vcs", "url": "https://github.com/weierophinney/zf2.git" }
]
```

and updating the zendframework requirement version to point to the branch:

```json
"zendframework/zendframework": "dev-hotfix/7448@dev",
```

Once the changes are made, run `composer update` to get the updated code.

Please let me know if this resolves the problem. If you still have lingering issues, please post the problematic input configurations so I can add them to the test suite.

This patch or one that builds on it (another contributor has another potentially interesting approach) will be merged to master by early next week, and will be in a forthcoming 2.4.1 release by mid-week.

**Comment by weierophinney** [comment]
Latest master branch of ZF2 has the updates; you can get those by specifying either `dev-master@dev` or `~2.4.0-dev@dev` for the ZF2 version; we'll be cutting a 2.4.1 release tomorrow, at which point a `composer update` will pick up the changes and address your needs.
