### ISSUE TITLE
Include Input filters/validators for non-body requests

### ISSUE THREAD

**Issue by robob4him** [zfcampus/zf-content-validation#47]
The content validation and filters only apply to requests with bodies (PUT, POST, etc) but could also easily apply to non-body requests such as GET. It's out-of-scope under the assumption fields in Apigility only apply to the target data, though, so this type of feature could end up being fulfilled as 'per-method filters/validators'.

Currently, that logic would just go into the resource.

**Comment by weierophinney** [comment]
This is a planned feature, but realistically, unless somebody contributes it, we won't be doing it before 2.0.

Additionally, such a feature *should* also have a corresponding UI - which is the main blocker for why we haven't pursued it yet (it's non-trivial to make a useful UI for this, we found).

**Comment by jeremygiberson** [comment]
I've submitted a pull request #64 regarding this issue. I created the patch to address one our requirements and didn't see this issue. But I'll take a look at providing corresponding UI patch for the added functionality too.

**Comment by weierophinney** [comment]
Closed with #64
