### ISSUE TITLE
Input Filter doesn't work with initializers

### ISSUE THREAD

**Issue by avirdz** [zfcampus/zf-content-validation#48]
I get the following error:

```json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Listed input filter \"Synergy\\V1\\Rest\\Group\\GroupInputFilter\" does not exist; cannot validate request"
}
```

In my Api Module class I have the following config:

```php
public function getInputFilterConfig()
    {
        return array(
            'initializers' => array(
                'Synergy\V1\Rest\Group\GroupInputFilter'  => 'Synergy\V1\Rest\Group\GroupInputFilterInitializer',
            ),
        );
    }
```

module.config.php
```php
 'zf-content-validation' => array(
        'Synergy\\V1\\Rest\\Group\\Controller' => array(
            'input_filter' => 'Synergy\V1\Rest\Group\GroupInputFilter',
        ),
    ),
```

Everything is ok if I change the key 'initializers' to 'invokables' but I need the initialization there and it's not working.

Thanks :)

**Comment by Wilt** [comment]
Don't you mean that you want to use a factory? An initializer is not supposed to return an `InputFilter` instance right?

**Comment by avirdz** [comment]
I used this pattern on ZF2 project, when I was migrating to apigility, initializers does not work anymore.

This was the code inside GroupInputFilterInitializer

```php
<?php

namespace Synergy\V1\Rest\Group;

use Zend\ServiceManager\InitializerInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class GroupInputFilterInitializer implements InitializerInterface
{
    public function initialize($instance, ServiceLocatorInterface $serviceLocator) 
    {
        if ($instance instanceof GroupInputFilter) {
            $instance->setGroupModel($serviceLocator->getServiceLocator()->get('Synergy\V1\Rest\Group\GroupModel'));
        }
    }
} 
```

**Comment by Wilt** [comment]
I think the problem might be that Apigility uses its own `InputFilterManager` instance.

**Comment by weierophinney** [comment]
@Wilt that's no longer true as of 1.1.0.

@avirdz Can you please raise this issue on https://github.com/zendframework/zend-inputfilter ? The issue is not specific to zf-content-validation, but exists upstream.
