### ISSUE TITLE
Validate a collection of Entities

### ISSUE THREAD

**Issue by santiph** [zfcampus/zf-content-validation#55]
I'm working with two entities using zf-apigility-doctrine module: Venues and Products.
A venue can have multiple products. Therefor, I need to POST/PATCH a Venue with an array of products, like this:
```
PATCH /venues/1
{
    "products": [
        {"id":2},
        {"id":5}
    ]   
}
```
This is the input_filter_specs I've configured:
```
            7 => array(
                'required' => true,
                'validators' => array(
                    0 => array(
                        'name' => 'ZF\\Apigility\\Doctrine\\Server\\Validator\\ObjectExists',
                        'options' => array(
                            'fields' => 'id',
                            'entity_class' => 'Db\\Entity\\Product',
                        ),
                    ),
                ),
                'filters' => array(),
                'name' => 'products',
            ),
```

But `DoctrineModule\Validator\ObjectExists` is being called with a single array with two values, 
```
array(2) {
  [0]=>
  array(1) {
    ["id"]=>
    int(2)
  }
  [1]=>
  array(1) {
    ["id"]=>
    int(5)
  }
}
```
when only 1 is expected
```
array(1) {
  [0]=>
  string(2) "id"
}
```

So, I think the problem here is how to detect when a collection is being sent for a specific attribute, that attribute as a collection, and then try to validate each of the elements individually?

**Comment by santiph** [comment]
I've found that I can add `is_collection` to the input_filter_specs, removing the validations so the service works well with more than one object being sent in the PATCH payload.
```
            7 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(),
                'name' => 'products',
                'is_collection' => true,
            ),
```
The problem now is this isn't validating that they're all valid and already exists. So... kind of work for me now, but it would be great to control that and return an error message if the client is trying to add an unexisting object to the collection.

**Comment by Wilt** [comment]
You have to setup an `CollectionInputFilter`. This allows you to point to an input-filter that will be used for each element in the collection. You do this by setting 'type' to 'Zend\InputFilter\CollectionInputFilter':

    'products' => array(
        'required' => true,
        'count' => ... optional count ...
        'input_filter' => ... input filter or input filter config to use for each element ...
        'type' => 'Zend\InputFilter\CollectionInputFilter',
    ),

Check also the question on StackOverflow here:

http://stackoverflow.com/questions/28668444/zf2-apigility-how-can-we-validate-collections-in-json-data
