### ISSUE TITLE
Duplication Fields when creating from apigility admin 

### ISSUE THREAD

**Issue by developer-devPHP** [zfcampus/zf-content-validation#79]
Your  last version 1.3.2  have a problem with creating new Fields. If you try to create any filed you got an duplication also same problem if you try to edit existing one.

Problem not related with apigility admin, because if I just changing version to 1.2.0 all working.

**Comment by webimpress** [comment]
@developer-devPHP that issue is resolved in #81 and fix is released in version [1.3.4](https://github.com/zfcampus/zf-content-validation/releases/tag/1.3.4)

Please confirm if it works to you and close the issue. Thanks!

**Comment by developer-devPHP** [comment]
@webimpress yes, last release not have this issue.
Issue closed.
Thanks.
