### ISSUE TITLE
apigility: filters in `input_filter_specs` not working

### ISSUE THREAD

**Issue by samsonasik** [zfcampus/zf-content-validation#85]
Steps to reproduce:

- define `input_filter_specs` config:
```php
        'ApiName\\V1\\Rpc\\Register\\Validator' => array(
            0 => array(
                'required' => true,
                'validators' => array(
                     0 => array(
                        'name' => 'Zend\\Validator\\StringLength',
                        'options' => array(
                            'min' => '1',
                            'max' => '100',
                        ),
                   ),
                ),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                        'options' => array(),
                    ),
                ),
                'name' => 'name',
                'description' => 'Version Name',
                'error_message' => 'Invalid version name',
            ),
        ),
```
- try send name:
```javascript
{ "name" : "foo   " }
```
- try echo `echo $this->bodyParam('name');` in controller 
```php
echo $this->bodyParam('name'); // echoed 'foo  ' with space in the right
```

with `Zend\\Filter\\StringTrim` definition, when a field named `name` sent with space in left and right, it should be trimmed, but at this case, it never trimmed. The `validators` is working, the filter is not. 

It happen with other filters too.

**Comment by samsonasik** [comment]
nvm, I should use $this->getInputFilter()->getValues() instead of $this->bodyParams();

**Comment by Wilt** [comment]
Are you sure?
Should the `bodyParams` not be pulled through the input-filter?

**Comment by Wilt** [comment]
This reminds me of this issue: https://github.com/zfcampus/zf-apigility-skeleton/issues/75

**Comment by samsonasik** [comment]
I don't know if that is on purpose as `$this->bodyParams()` not include the inputfilter

**Comment by Wilt** [comment]
Maybe good to reopen your issue and await feedback? I am kind of interested...

**Comment by samsonasik** [comment]
re-open

**Comment by webimpress** [comment]
@samsonasik @Wilt It is expected behaviour in apigility, please read this documentation:
https://apigility.org/documentation/content-validation/basic-usage#accessing-filtered-data

> `zf-content-validation` leaves the request intact once validation is complete.

If you want to get filtered data you have to get them from input filter.

Please have a look also on similar issue https://github.com/zfcampus/zf-apigility/issues/45
and @weierophinney answers.

**Comment by samsonasik** [comment]
Thank you, re-closed.

**Comment by Wilt** [comment]
@webimpress  Thanks!
